### ISSUE TITLE
client side?

### ISSUE THREAD

**Issue by chovy** [lovell/limax#11]
How well does this work client side?

I was using `node-slug` but on the client side it requires a 2MB file for utf8 characters to load which isn't realistic.

**Comment by lovell** [comment]
Hello, the support for Pinyin in `limax` is backed by the the native (C++) [`nodejieba`](https://www.npmjs.com/package/nodejieba) module, which is used for word segmentation. This won't work on the client side.

If you need client side support and can live without transliteration of Chinese and Japanese scripts, then I recommend [speakingurl.min.js](https://github.com/pid/speakingurl/blob/master/speakingurl.min.js), which weighs in at ~16KB.

**Comment by lovell** [comment]
Hopefully this answered you question - feel free to re-open if not.
