### ISSUE TITLE
Number slugs

### ISSUE THREAD

**Issue by dvrylc** [lovell/limax#12]
I've realised that slugs involving numbers behave a little weirdly.

```
> limax('12')
'12'

> limax('123')
'1-2-3'

> limax('12345')
'1-234-5'
```

Is this the intended behavior and if so, why?
Thanks!

**Comment by lovell** [comment]
Oh, that certainly doesn't look like any intended behaviour. I'll need to take a closer look to see where it's going wrong - thanks for reporting!

**Comment by dvrylc** [comment]
I believe it has to do with this - https://github.com/lovell/limax/blob/master/lib/limax.js#L16. 

The regular expression there seems incorrect, introduced in 27dca0e2ef499950445b0f4c272c859ac395cd5e to allow something like `one2three` to be slugified to `one-2-three`. 

Would a PR be welcome?

**Comment by lovell** [comment]
Great, that'll be it, the `\S` parts of that regex need to exclude digits. PR very much welcome, thank you.
