### ISSUE TITLE
Numbers inside a word

### ISSUE THREAD

**Issue by arjanfrans** [lovell/limax#14]
`slug('test22test')`

This returns: `test-22-test`. I would expect this to return `test22test`. Looks like this is related to the regex mentioned in #12.

Is this intended behavior? And if so, why?

**Comment by lovell** [comment]
Hello, I think was the original intended behaviour, although it doesn't appear to be documented :(

Pinyin transliteration uses numbers to represent word tone, which can conflict with "words" containing numbers such as prices. I guess this makes most sense when using Mandarin Chinese input, although some people may want consistency across all possible input languages.

I'd be happy to accept a PR to add something like a `separateNumbers` option to make this behaviour optional.

**Comment by arjanfrans** [comment]
Thanks, I'll try to implement something and send a PR.

**Comment by lovell** [comment]
v1.4.0 now available with your addition, thank you!
