### ISSUE TITLE
Thank you for making this!

### ISSUE THREAD

**Issue by niftylettuce** [lovell/limax#18]

**Comment by niftylettuce** [comment]
I had used `slug-rfc`, `slug`, and `speakingurl`.  Where can I donate to you for your work here, sharp, attention?  I use it all.  You rock.  Building https://github.com/crocodilejs/crocodile-node-mvc-framework

**Comment by lovell** [comment]
Thank you for the positive feedback, I'm glad to hear you're finding it all useful; tell all your friends!

(If you have a desire to pay, please make your donation to a homelessness charity near you.)
