### ISSUE TITLE
Custom replacement doesn't probably work with non-latin chars

### ISSUE THREAD

**Issue by saamo** [lovell/limax#22]
```js
const options = { custom: ["."] };

const wrong = "中文.pdf";
console.log(limax(wrong, options)); // produces `zhong1-wen2-pdf`

const correct = "chinese.pdf";
console.log(limax(correct, options)); // produces `chinese.pdf`
```

It doesn't convert dot to dot as it is supposed to do. Am I missing something?

**Comment by lovell** [comment]
Hello, the `custom` option is a new feature - see #20. It looks like it's failing for Chinese at [limax.js#L40](https://github.com/lovell/limax/blob/master/lib/limax.js#L40). The logic/regex should probably be modified to handle custom characters, if any. A PR to address this would be most welcome, as always.

**Comment by lovell** [comment]
I've finally had a chance to take a deeper look at this.

When `custom` is passed as an Array, the list of chars are allowed to appear in the output and will not be removed or replaced. They do not have any other special meaning, so I think the output of
```javascript
limax("中文.pdf", { custom: ["."] });
```
...should really be `zhong1-wen2-.pdf` according to the documented behaviour, as it has been configured to allow the dot as a "normal" character.

This means there's still a bug, but the "fixed" output will not be what you're expecting.

Your use case requires two separators, which is slightly beyond the scope of this module as it currently stands. Perhaps you can add custom logic to your code to temporarily split on the dot, something like:

```javascript
"中文.pdf".split(".").map(limax).join(".");
```

**Comment by lovell** [comment]
Commit e9edb94 includes this use case as a test and the fix for it, thank you for reporting this.

**Comment by lovell** [comment]
v1.6.0 now available.
