### ISSUE TITLE
Should we separateNumbers by default?

### ISSUE THREAD

**Issue by niftylettuce** [lovell/limax#24]
I don't think this is what most users intend to have as output (e.g. `foo123foo` => `foo-123-foo`) - and other packages like `slug`, `speakingurl`, etc do not do this by default as far as I know.

**Comment by niftylettuce** [comment]
Otherwise, excellent work as always @lovell 👍

**Comment by lovell** [comment]
Hello, number separation makes a little sense in non-Latin scripts where Arabic numerals (0-9) are used, or at least I recall that's the original rational behind this feature.

Happy for a PR to switch the default behaviour if you're able. This would need to be released with a major version bump.

**Comment by lovell** [comment]
v2.0.0 now available with `separateNumbers` defaulting to `false`.
