### ISSUE TITLE
bug: numbers like "404" are separating to "4-4"

### ISSUE THREAD

**Issue by niftylettuce** [lovell/limax#25]
related to #24 this I believe is due to this line <https://github.com/lovell/limax/blob/master/lib/limax.js#L54-L56>

expected result is `404`, however I get `4-4`

I think I will need to revert to using `speakingurl` 😦

**Comment by lovell** [comment]
Hello, I added the following test cases that pass for me when run locally.
```javascript
assert.strictEqual(
  slug('404', { separateNumbers: true }),
  '404'
);
assert.strictEqual(
  slug('404', { separateNumbers: false }),
  '404'
);
assert.strictEqual(
  slug('状态404页面未找到', { separateNumbers: true }),
  'zhuang4-tai4-404-ye4-mian4-wei4-zhao3-dao4'
);
assert.strictEqual(
  slug('状态404页面未找到', { separateNumbers: false }),
  'zhuang4-tai4-404-ye4-mian4-wei4-zhao3-dao4'
);
```
Are you able to provide more information on the failing case such as any other options used?

**Comment by lovell** [comment]
The test cases from the comment above are now in the unit tests.

https://github.com/lovell/limax/blob/02f7748913f7883dfef67ff256eea34021de5829/test/unit.js#L66-L82
