### ISSUE TITLE
What are the enumeration of lang parameters?

### ISSUE THREAD

**Issue by baijunjie** [lovell/limax#26]
`zh`、`ja` ?
`zh-CN` or `zh-TW` ?

**Comment by lovell** [comment]
Hello, the `lang` parameter can be one of those listed at https://github.com/pid/speakingurl#getsluginput-options

It's a good question though, as at the moment use of Chinese or Japanese is auto-detected only. Setting `lang` to `ja` will actually *prevent* an attempt at Hepburn transliteration - https://github.com/lovell/limax/blob/master/lib/limax.js#L25 - this doesn't seem right to me, so should probably be fixed.

**Comment by lovell** [comment]
Commit ca7de19 ensures transliteration occurs when `lang` is explicitly set to `ja` or `zh` (or variants). Thanks for reporting this.

**Comment by lovell** [comment]
v1.6.0 now available.
