### ISSUE TITLE
Mention mongoose-slug-plugin use with limax?

### ISSUE THREAD

**Issue by niftylettuce** [lovell/limax#27]
Using this package for generating slugs to use in URL's is probably fairly common.  I'd suggest possibly putting a note in README such as...

> **Using Mongoose?**  Try `mongoose-slug-plugin` at <https://github.com/ladjs/mongoose-slug-plugin>!

Or something similar - the reason being is because a lot of Node.js users use MongoDB (Mongo is to Node.js what SQL is to Ruby imo).  And the most popular ODM for MongoDB is Mongoose, therefore I figured it'd help out with confusion (considering there's dozens of poorly maintained, untested, and unpluggable slug helpers on NPM right now for Mongoose).

**Comment by lovell** [comment]
It look like mongoose-slug-plugin depends on speakingurl rather than limax.

https://github.com/pid/speakingurl/issues/114
https://github.com/Zertz/mollusc/issues/42
https://github.com/simov/slugify/issues/20

Please don't cross-post.

**Comment by niftylettuce** [comment]
It's pluggable though to be used with `limax`.  The reason I didn't use `limax` out of the box is because it is not SEO-friendly and I had these issues in the past https://github.com/lovell/limax/issues/25 and https://github.com/lovell/limax/issues/24.

I built this to help the community... https://www.npmjs.com/search?q=mongoose+slug "30 packages found"... 😦

**Comment by lovell** [comment]
`limax` has always depended upon `speakingurl` and I'm pleased to see it continues to be well-maintained, so good choice.

I believe `limax` is used where Romanisation of Chinese and Japanese scripts is also required, the most common use case being multi-locale static site builders. I'm not aware of anyone using it dynamically such as with Mongo.

#25 stalled waiting for feedback - if you're now able to help that would be great.
