### ISSUE TITLE
Unsupported languages

### ISSUE THREAD

**Issue by luminous8** [lovell/limax#31]
Hi there, 

Is there a solution to have a backup slug for all the languages that limax doesn't support?

Few exemple that I have in mind 
"하용수" / "🌴🍰🌕💋🍪" / "▲"

Thanks!

**Comment by lovell** [comment]
Hello, perhaps try using the [unicode](https://www.npmjs.com/package/unicode) module to extract the `name` field for each symbol first so you'd get something like `palm-tree-cake-full-moon...` etc.
