### ISSUE TITLE
how replace ' by -

### ISSUE THREAD

**Issue by ddtraceweb** [lovell/limax#36]
i try this

slug("j'aime ça", custom: { "'": "-" }}) and i have //jaime-ca

i would like have //j-aime-ca

thanks,

**Comment by lovell** [comment]
Bonjour, I'd be very happy to accept a PR, if you're able, to make the following logic optional:

https://github.com/lovell/limax/blob/6c3015b694ca4f5938ce7e8a0b1911db48edb20e/lib/limax.js#L17-L18

The API could look something like:
```js
limax("j'aime ça", { separateApostrophes: true }) // PROPOSED API
```

**Comment by ddtraceweb** [comment]
@lovell it's done :)

best regards.

**Comment by lovell** [comment]
v2.1.0 is now available with this feature, thank you for the PR.
