### ISSUE TITLE
Getting "limax_1.default is not a function"

### ISSUE THREAD

**Issue by Hatko** [lovell/limax#40]
In a typescript, NestJS project I'm getting:

`limax_1.default is not a function`

On this code:

```
import slug from 'limax'

slug(name)
```

The generated JS code looks like this:

```
const limax_1 = require("limax");

limax_1.default(name)
```

**Comment by Hatko** [comment]
Fixed for now changing to:

```
const slug = require('limax')

// @ts-ignore
slug(name)
```

**Comment by lovell** [comment]
Unless there's a typo in the first post, I think the problem may be that

> import slug from 'limax'

is most definitely not the same thing as 

> const limax_1 = require("climax");

**Comment by Hatko** [comment]
@lovell Thanks for getting back so fast!

:D fixed!

**Comment by lovell** [comment]
You'll probably need to set [esModuleInterop](https://www.typescriptlang.org/tsconfig#esModuleInterop) to `true`.

**Comment by Hatko** [comment]
Thanks!
