### ISSUE TITLE
Add a changelog on release?

### ISSUE THREAD

**Issue by OmgImAlexis** [lovell/limax#41]
Currently if users got the release tab they have no clue what's changed between releases.

Any chance you could start adding those?

**Comment by lovell** [comment]
Yes, good idea, commit 5b3e6e2 adds this in a mostly-automated way, which is hopefully better than nothing at all.

**Comment by lovell** [comment]
I've just published v4.0.0 and included the semi-automated changelog file in the package pushed to npm.
