### ISSUE TITLE
Macron should default to non-macron character not hyphen

### ISSUE THREAD

**Issue by Betree** [lovell/limax#44]
Characters with a marcron (e.g. `ō`) should default to the non-macron version of that letter, not a hyphen.

**Example**: `Pōneke`
- Expected result: `poneke`
- Current result: `p-neke`

I'm interested in making a contribution to the repo if maintainers agree on the intent of this issue!

**Comment by lovell** [comment]
Hello, yes I agree, we should definitely support this.

The current character map we use is https://github.com/pid/speakingurl/blob/master/lib/speakingurl.js but it looks like that dependency is no longer maintained so submitting it upstream won't help.

A possible alternative character map is https://github.com/sindresorhus/transliterate/blob/main/replacements.js but this has gone ESM-only, which I don't intend to do here.

Perhaps it's time to either fork or directly add the speakingurl logic as part of this repo and make the changes we need? Suggestions welcome.

**Comment by lovell** [comment]
Thanks again for the PR, v4.0.0 now available.
