### ISSUE TITLE
Chinese Pinyin is not accurate

### ISSUE THREAD

**Issue by starcsb** [lovell/limax#47]
I use limax to display some chinese pinyin, but I found the result of chinese pinyin is not accurate, for example:
```js
const pinyin = slug('路上的行人'); // lu4-shang4-de-hang2-ren2
// The correct result of above should be // lu4-shang-de-xing2-ren2
```
I suggest to replace [pinyin](https://github.com/hotoo/pinyin) by [pinyin-pro](https://github.com/zh-lx/pinyin-pro), because [pinyin-pro](https://github.com/zh-lx/pinyin-pro) has higher accuracy, better performance, and no dependencies.

The accuray about chinese pinyin of `pinyin-pro` is `99.744%`, and `pinyin` is only `97.844%`. You can see the [comparsion](https://github.com/zh-lx/pinyin-pro#-%E7%AB%9E%E5%93%81%E5%AF%B9%E6%AF%94)

**Comment by lovell** [comment]
It looks like this will be fixed upstream in the `@napi-rs/pinyin` package via https://github.com/mozillazg/rust-pinyin/pull/64

**Comment by starcsb** [comment]
> It looks like this will be fixed upstream in the `@napi-rs/pinyin` package via [mozillazg/rust-pinyin#64](https://github.com/mozillazg/rust-pinyin/pull/64)

I don't think [mozillazg/rust-pinyin#64](https://github.com/mozillazg/rust-pinyin/pull/64) can improve accuracy of Chinese pinyin. [mozillazg/rust-pinyin#64](https://github.com/mozillazg/rust-pinyin/pull/64) only modified a few pinyin without modifying the underlying data. As far as I know, [pinyin-pro](https://github.com/zh-lx/pinyin-pro) has crawled, filtered, and prioritized the vast majority of Chinese vocabulary, this is the key to ensuring very high accuracy.

**Comment by lovell** [comment]
Oh, I see what you mean, pinyin-pro does look really good.

I'd be happy to accept a PR that switches to using it, and your example of the hang/xing (adjective/adverb) mistake would be a good addition to the tests as well.

**Comment by Brooooooklyn** [comment]
> const pinyin = slug('路上的行人'); // lu4-shang4-de-hang2-ren2
> // The correct result of above should be // lu4-shang4-de-xing2-ren2

@starcsb this case was fixed by https://github.com/mozillazg/rust-pinyin/pull/64

Thanks for reporting; I'll update the [`pinyin-data`](https://github.com/mozillazg/pinyin-data)

**Comment by starcsb** [comment]
@lovell @Brooooooklyn I have installed the latest version(1.7.3) of `@napi-rs/pinyin` and test the accuracy of it with the benchmark, it improved to `97.485%` from `97.433%`, but there is still a significant difference in accuracy compared to `pinyin-pro`.

**Comment by lovell** [comment]
v4.1.0 now available, thank you for the PR.
