### ISSUE TITLE
change pinyin2 to pinyin

### ISSUE THREAD

**Issue by ZheFeng** [lovell/limax#5]
pinyin2 (https://github.com/princetoad/pinyin.js) is actually forked from pinyin (https://github.com/hotoo/pinyin).

If you check these 2 project, you can find pinyin is more activity and most recent change happens. So why not change to pinyin?

**Comment by lovell** [comment]
I can't remember the exact reason why the fork was originally selected. Perhaps it was better-maintained at the time of original implementation.

The original repo is definitely looking far healthier, thank you for this suggestion. I'm happy to accept a PR with the change if you're comfortable doing this. If so, feel free to add any test cases that would have failed with `pinyin2` but that will work with `pinyin`.

**Comment by ZheFeng** [comment]
Understand, I'm happy to do it. :)

**Comment by ZheFeng** [comment]
Great.
https://github.com/lovell/limax/pull/6#issuecomment-121947350
