### ISSUE TITLE
Problem with installing on nodejs v.0.12.9

### ISSUE THREAD

**Issue by daniymilner** [lovell/limax#8]
We are using your module in project with nodejs v.0.12.9.

Your dependency pinyin v2.7.0 begin to use ES6 witch is not supported in nodejs v.0.12.9 and we have a problem with installing limax. 

Please solve this problem or we will use our fork in future.

**Comment by lovell** [comment]
Ah, I see what you mean. I guess the `pinyin`module isn't using strict semantic versioning.

I'd be happy to accept a PR that "pins" its version to v2.6.2.

Thanks for reporting!

**Comment by lovell** [comment]
Thanks for the PR to address this.

It'll be published to npm as v1.2.0 due to the upgrade of the speakingurl dependency (for improvements to Russian transliteration).
